<a href="https://colab.research.google.com/github/rabin20-04/CPP-codex/blob/main/Heart_diesease_prediction_RF/heat_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import  SVC
from sklearn.linear_model import LogisticRegression

In [2]:
df1=pd.read_csv("/content/heart.csv")
df2=pd.read_csv("/content/heart _1.csv")

In [3]:
df1.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
df2.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
print(df1.shape)
print(df2.shape)

(1025, 14)
(303, 14)

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [9]:
df1.describe().T

           count        mean        std    min    25%    50%    75%    max
age       1025.0   54.434146   9.072290   29.0   48.0   56.0   61.0   77.0
sex       1025.0    0.695610   0.460373    0.0    0.0    1.0    1.0    1.0
cp        1025.0    0.942439   1.029641    0.0    0.0    1.0    2.0    3.0
trestbps  1025.0  131.611707  17.516718   94.0  120.0  130.0  140.0  200.0
chol      1025.0  246.000000  51.592510  126.0  211.0  240.0  275.0  564.0
fbs       1025.0    0.149268   0.356527    0.0    0.0    0.0    0.0    1.0
restecg   1025.0    0.529756   0.527878    0.0    0.0    1.0    1.0    2.0
thalach   1025.0  149.114146  23.005724   71.0  132.0  152.0  166.0  202.0
exang     1025.0    0.336585   0.472772    0.0    0.0    0.0    1.0    1.0
oldpeak   1025.0    1.071512   1.175053    0.0    0.0    0.8    1.8    6.2
slope     1025.0    1.385366   0.617755    0.0    1.0    1.0    2.0    2.0
ca        1025.0    0.754146   1.030798    0.0    0.0    0.0    1.0    4.0
thal      1025.0    2.323902   0.620660    0.0    2.0    2.0    3.0    3.0
target    1025.0    0.513171   0.500070    0.0    0.0    1.0    1.0    1.0

In [16]:
X_1=df1.iloc[:,0:-1]
X_2=df2.iloc[:,0:-1]
Y_1=df1.loc[:,"target"]
Y_2=df2.loc[:,"target"]

In [14]:
X_2.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [15]:
from sklearn.model_selection import train_test_split

In [21]:
x1_train,x1_test,y1_train,y1_test=train_test_split(X_1,Y_1,test_size=0.2,random_state=2)
x2_train,x2_test,y2_train,y2_test=train_test_split(X_2,Y_2,test_size=0.2,random_state=2)

In [22]:
print(x1_train.shape,x1_test.shape)
print(x2_train.shape,x2_test.shape)

(820, 13) (205, 13)
(242, 13) (61, 13)

# Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
rfc1=RandomForestClassifier()
rfc2=RandomForestClassifier()

In [24]:
rfc1.fit(x1_train,y1_train)
rfc2.fit(x2_train,y2_train)

RandomForestClassifier()

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
y1_predict=rfc1.predict(x1_test)
y2_predict=rfc2.predict(x2_test)

In [27]:
print(accuracy_score(y1_test,y1_predict))
print(accuracy_score(y2_test,y2_predict))

1.0
0.9016393442622951

## SVC

In [31]:
svc1=SVC()
svc2=SVC()

In [32]:
svc1.fit(x1_train,y1_train)
svc2.fit(x2_train,y2_train)

SVC()

In [34]:
y1_predict=svc1.predict(x1_test)
y2_predict=svc2.predict(x2_test)
print("df1_accu:",accuracy_score(y1_test,y1_predict))
print("df2_accu:",accuracy_score(y2_test,y2_predict))

df1_accu: 0.7317073170731707
df2_accu: 0.6721311475409836

# LogisticRegression

In [38]:
lr1=LogisticRegression()
lr2=LogisticRegression()

In [39]:
lr1.fit(x1_train,y1_train)
lr2.fit(x2_train,y2_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [40]:
y1_predict=lr1.predict(x1_test)
y2_predict=lr2.predict(x2_test)
print("df1_accu:",accuracy_score(y1_test,y1_predict))
print("df2_accu:",accuracy_score(y2_test,y2_predict))

df1_accu: 0.8536585365853658
df2_accu: 0.9016393442622951

# GradientBoostingClassifier

In [35]:
gbc1= GradientBoostingClassifier()
gbc2= GradientBoostingClassifier()

In [36]:
gbc1.fit(x1_train,y1_train)
gbc2.fit(x2_train,y2_train)

GradientBoostingClassifier()

In [37]:
y1_predict=gbc1.predict(x1_test)
y2_predict=gbc2.predict(x2_test)
print("df1_accu:",accuracy_score(y1_test,y1_predict))
print("df2_accu:",accuracy_score(y2_test,y2_predict))

df1_accu: 0.9707317073170731
df2_accu: 0.8852459016393442